services:
  server:
    container_name: ecomers-api
    build: .
    image: ecomersapi
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    container_name: sql_server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=P@ssw0rd123!
    volumes:
      - sql-server-data:/var/opt/mssql
volumes:
  sql-server-data:
    name: sql-data